version: '3.8'
services:
  db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: prismaadmin
      POSTGRES_PASSWORD: prismaadmin
      POSTGRES_DB: homelibraryservice
    networks:
      - homelibrary
networks:
    homelibrary:

